config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'create_new_splitter' }
  
  root 'slides#index'
  
  resources :announcements
  resources :clogos
  resources :announcements do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :artists
  resources :artists do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :admins, :path => "admin"
  resources :works, :path => "placements"
  resources :works do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :releases
  resources :slides, :path => "news"
  resources :releases do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  # resources :customs, :path => "composition"
#   resources :customs do
#     post :update_row_order, on: :collection
#     collection {post :import}
#   end
  resources :researches, :path => "researchlondon"
  resources :researches do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :contacts, :path => "contact"
  resources :share_closes
  resources :newsletters
  resources :showreels
  resources :showreels do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :customvideos
  
  match "admins/artists" => "admins#artists", via: [:get, :post]
  match "admins/customs" => "admins#customs", via: [:get, :post]
  match "admins/placements" => "admins#placements", via: [:get, :post]
  match "admins/releases" => "admins#releases", via: [:get, :post]
  match "admins/customs" => "admins#customs", via: [:get, :post]
  match "admins/researches" => "admins#researches", via: [:get, :post]
  match "admins/slideshow" => "admins#slideshow", via: [:get, :post]
  match "admins/announcements" => "admins#announcements", via: [:get, :post]
  match "admins/newsletter" => "admins#newsletter", via: [:get, :post]
  match "admins/newsletter_blast" => "admins#newsletter_blast", via: [:get, :post]
  match "admins/showreel" => "admins#showreel", via: [:get, :post]
  match "compositions/showreel" => "customs#showreel", via: [:get, :post]
  
end

app/models/artist.rb
class Artist < ActiveRecord::Base

  has_many :releases
  belongs_to :slide
  before_update { |artist| 
    if artist.soundcloud_changed? then
      input_string = artist.soundcloud.gsub(/\s+/, "").to_s
      str1_markerstring = "playlists/"
      str2_markerstring = "&color"
      input_string_chop = input_string[/#{str1_markerstring}(.*?)#{str2_markerstring}/m, 1]
      artist.soundcloud = input_string_chop
    end
  }
  before_save :upcase_fields
  before_validation :make_first, on: :create
  
  def make_first
    self.row_order_position ||= :first
  end
  include Filterable
  
  def upcase_fields
    unless self.slide_title.to_s.strip.empty?
      self.slide_title.upcase!
    end
    unless self.slide_title2.to_s.strip.empty?
      self.slide_title2.upcase!
    end
    unless self.artist_name.to_s.strip.empty?
      self.artist_name.upcase!
    end
    unless self.track_name.to_s.strip.empty?
      self.track_name.upcase!
    end
  end
  
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  
  require 'csv'
  
  def self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      artist = Artist.find_or_initialize_by(name: row["name"])
      artist.assign_attributes(row.to_hash)
      artist.save!
    end
  end
  
  include RankedModel
  ranks :row_order
  
  def slug_candidates
    if self.slug
      "#{artist_name}-#{id}"
    else
      "#{artist_name}"
    end
  end
  
  if Rails.env.development?
    has_attached_file :image, IMAGE_PAPERCLIP_STORAGE_OPTS
  else
    has_attached_file :image,
    :convert_options => { :all => '-quality 92' }, 
    styles: {main: '300x300>'},
    :storage => :s3,
    :s3_credentials => {
    :access_key_id => ENV['S3_KEY'],
    :secret_access_key => ENV['S3_SECRET'] },
    :url => ':s3_alias_url',
    :s3_host_alias => 'd9gj9tfjl21as.cloudfront.net', 
    :bucket => 'split-two',
    :path => "artists/images/:id_partition/:style/:filename"
  end
  
  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  if Rails.env.development?
    has_attached_file :fb_image, FB_IMAGE_PAPERCLIP_STORAGE_OPTS
  else
    has_attached_file :fb_image,
    :convert_options => { :all => '-quality 92' }, 
    styles: {main: '1200x630>'},
    :storage => :s3,
    :s3_credentials => {
    :access_key_id => ENV['S3_KEY'],
    :secret_access_key => ENV['S3_SECRET'] },
    :url => ':s3_alias_url',
    :s3_host_alias => 'd9gj9tfjl21as.cloudfront.net', 
    :bucket => 'split-two',
    :path => "artists/fb_images/:id_partition/:style/:filename"
  end
  
  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :fb_image, :content_type => /\Aimage\/.*\Z/
  
  if Rails.env.development?
    has_attached_file :slide_image, SLIDE_PAPERCLIP_STORAGE_OPTS
  else
    has_attached_file :slide_image,
    :convert_options => { :all => '-quality 92' }, 
    styles: {main: '1115x952>'},
    :storage => :s3,
    :s3_credentials => {
    :access_key_id => ENV['S3_KEY'],
    :secret_access_key => ENV['S3_SECRET'] },
    :url => ':s3_alias_url',
    :s3_host_alias => 'd9gj9tfjl21as.cloudfront.net', 
    :bucket => 'split-two',
    :path => "artists/slide_images/:id_partition/:style/:filename"
  end
  
  if Rails.env.development?
    has_attached_file :hero, HERO_PAPERCLIP_STORAGE_OPTS
  else
    has_attached_file :hero,
    :convert_options => { :all => '-quality 92' }, 
    styles: {main: '1115x952>'},
    :storage => :s3,
    :s3_credentials => {
    :access_key_id => ENV['S3_KEY'],
    :secret_access_key => ENV['S3_SECRET'] },
    :url => ':s3_alias_url',
    :s3_host_alias => 'd9gj9tfjl21as.cloudfront.net', 
    :bucket => 'split-two',
    :path => "artists/slide_images/:id_partition/:style/:filename"
  end
  
  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :slide_image, :content_type => /\Aimage\/.*\Z/
  
  def self.search(search)
    if search.to_s.include? "slide"
      where('slideshow = TRUE') # Needs to be - where('slideshow = "t"') in development and - where('slideshow = TRUE') in production
    elsif search.to_s.include? "news"
      where('newsletter = TRUE')
    elsif search
      where('LOWER(slide_title) LIKE :search OR LOWER(slide_title2) LIKE :search 
      OR LOWER(artist_name) LIKE :search OR LOWER(vimeo) LIKE :search OR LOWER(platform) LIKE :search', search: "%#{search}%")
    else
      all
    end
  end
  
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!, :except => ["index", "show"]
  
    def new
      @artist = Artist.new
    end

    def create
      @artist = Artist.create(artist_params)
      respond_to do |format|
        format.html { redirect_to admins_artists_path }
      end
    end

    def edit
      @artist = Artist.find_by_slug(params[:id])
    end

    def update   
      @artist = Artist.find_by_slug(params[:id])
      if @artist.update_attributes(artist_params)
        respond_to do |format|
         format.html { redirect_to admins_artists_path }
         format.json { render :json => @artist }
        end
      else
        respond_to do |format|
          format.html { render :action  => :edit } # edit.html.erb
          format.json { render :nothing =>  true }
        end
      end
    end

    def destroy
      @artist = Artist.find_by_slug(params[:id])
      @artist.destroy
      respond_to do |format|
        format.html { redirect_to admins_artists_path }
      end
    end
    
    def import
      Artist.import(params[:file])
      redirect_to admins_artists_path, notice: "Artists imported!" 
    end
    
    def index
      @artists = Artist.rank(:row_order).all
      set_meta_tags :og => {
        :url => "#{@currentUrl}",
        :title    => 'Split Music | Artists',
        :description => '21st Century Music Publishing | Unique Music to Picture'
      }
      set_meta_tags twitter: {
        card: "summary_large_image",
        site: "@fairsplitmusic",
        title: "Split Music | Artists",
        description: "21st Century Music Publishing | Unique Music to Picture"
      }
    end
    
    def show
      @artist = Artist.find_by_slug(params[:id])
      set_meta_tags og: {
        url: "#{@currentUrl}",
        image: "#{@artist.fb_image}",
        title: "#{@artist.artist_name}",
        description: "#{@artist.description}",
        type: "musician"
      }
      set_meta_tags twitter: {
        card: "summary_large_image",
        site: "@fairsplitmusic",
        title: "#{@artist.artist_name}",
        description: "#{@artist.description}",
        image: "#{@artist.fb_image}"
      }
      render :show, flush: true
    end

    def update_row_order
      @artist = Artist.find(artist_params[:artist_id])
      @artist.row_order_position = artist_params[:row_order_position]
      @artist.save
      render nothing: true # this is a POST action, updates sent via AJAX, no view rendered
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end
    
    def artist_params
      params.require(:artist).permit(:artist_id, :artist_name, :description, :soundcloud, :fb_url, :twitter_name, :image, :fb_image, :hero, :row_order_position, 
      :slideshow, :slide_image, :slide_title, :slide_title2, :slide_title3, :vimeo, :Slideshowposition, :platform, :nltitle, :nltitle2, :nlsubtitle, :nldescription, 
      :nlsubtitle, :newsletter, :newsletterposition, :track_name)
    end

end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/views/artists/_form.html.erb
<div class="deviseStyling abouts marginTopOverride canScroll">
	<h2 class="titles">Add your artist here!</h2>
	<%= bootstrap_form_for(@artist) do |f| %>
		<div class="col-md-12" style="background-color: rgba(113, 113, 113, 0.5);padding:10px;border-radius:6px;margin:0px 0px 10px 0px">
			<h2 style="margin:10px;">IMAGES</h2>
			<div class="vimeoSectionInForm">
				<div class="textField"><%= f.file_field :image, label: "Square image (crop to 400px X 400px)" %>
					<% if @artist.image.exists? %>
						<p class="existingImageName">{ Current Image: "<%= @artist.image_file_name %>" }</p>
					<% end %>
				</div>
				<div class="textField"><%= f.file_field :slide_image, label: "Slideshow image (crop to 1115px X 952px)" %>
					<% if @artist.slide_image.exists? %>
						<p class="existingImageName">{ Current Image: "<%= @artist.slide_image_file_name %>" }</p>
					<% end %>
				</div>
				<div class="textField"><%= f.file_field :fb_image, label: "Facebook image (crop to 1200px X 630px)" %>
					<% if @artist.fb_image.exists? %>
						<p class="existingImageName">{ Current Image: "<%= @artist.fb_image_file_name %>" }</p>
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-6" style="background-color: rgba(113, 113, 113, 0.5);padding:10px;border-radius:6px;margin:0px 0px 0px 0px">
			<h2 style="margin:10px;">MAIN PLACEMENT CONTENT</h2>
			<div class="vimeoSectionInForm">
				<div class="textField2"><%= f.text_field :slide_title, label: "Line1 A (Slide Title 1)" %></div>
				<div class="textField2"><%= f.text_field :slide_title2, label: "Line1 B (Slide Title 2)" %></div>
				<div class="textField2"><%= f.text_field :artist_name, label: "Line2 A (Artist Name)" %></div>
				<div class="textField2"><%= f.text_field :track_name, label: "Line2 B" %></div>
				<div class="textField2"><%= f.text_field :vimeo, label: "Video URL" %></div>
				<div class="textField2">
					<%= f.select :platform, options_for_select(["vimeo", "youtube"], @artist.platform) %>
				</div>
				<div class="textField smallText"><%= f.check_box :slideshow, label: "Add to slideshow?" %></div>
			</div>
			<div class="vimeoSectionInForm"><%= f.text_area :description, label: "Description" %></div>
		</div>
		<div class="col-md-6" style="background-color: rgba(113, 113, 113, 0.5);padding:10px;border-radius:6px;width:48%; margin:0px 1%;">
			<h2 style="margin:10px;">NEWSLETTER CONTENT</h2>
			<div class="vimeoSectionInForm">
				<div class="textField smallText"><%= f.check_box :newsletter, label: "Add to newsletter?" %></div>
				<div class="textField3"><%= f.file_field :hero, label: "Newsletter hero image (crop to 564px X 235px before upload)" %>
					<% if @artist.hero.exists? %>
						<p class="existingImageName">{ Current Image: "<%= @artist.hero_file_name %>" }</p>
					<% end %>
				</div>
			</div>
			<div class="vimeoSectionInForm">
				<div class="textField2"><%= f.text_field :nltitle, label: "Newsletter title" %></div>
				<div class="textField2"><%= f.text_field :nlsubtitle, label: "Newsletter title 2" %></div>
			</div>
			<div class="vimeoSectionInForm"><%= f.text_area :nldescription, label: "Newsletter description" %></div>
		</div>
	  	<div class="buttons" style="float:left;clear:both;margin:25px -6px;">
			<div class="submitLarge"><%= f.submit 'Submit', class: "btn btn-success"  %></div>
			<div class="cancelButton"><%= link_to('Cancel', :back ,class: "btn btn-success")  %></div>
		</div>
	<% end %>
</div>

app/views/artists/edit.html.erb
<%= render 'form' %>

app/views/artists/index.html.erb
<div class="canScroll" id="artistScrollPosition">
	<div class="col-md-12">
		<% @artists.each do |artist| %>
		<input type="hidden" value=<%= artist.id %> class="modal-object-id">
		<a href="<%= artist_path(artist) %>" class="positionButtonArtist">
			<div class="col-md-4b artistContainer">
				<div class="artist">
					<div class="info-wrapper">
						<h5 class="colour notBold"><%= artist.artist_name %></h5>
						<!--<hr class="dots"/>
						<p class="artistDescription"><%#= truncate(artist.description, :length => 220, :separator => ' ') %></p>-->
					</div>
					<%= image_tag "https://d9gj9tfjl21as.cloudfront.net/ajaxBig2.gif", data:{ src: image_path(artist.image) }, class: 'lazy lazyload' %>
				</div>
			</div>
		</a>
		<% end %>
	</div>
</div>

app/views/artists/new.html.erb
<%= render 'form' %>

app/views/artists/show.html.erb
<div class="canScroll">	
	<div class="artistInfo">
		<%= link_to '', artists_path, :class => "closeIcon" %>
		<h1 class="artistName titleSize1"><%= @artist.artist_name %></h1>
		<hr class="artistSeparator" />
		<% if @artist.vimeo? %>
			<div class="videoMaster">
				<div class="videoDesktop desktopME">
					<div class="fitvids responsiveVideo2">
						<div class="plyr js-player">
						    <div data-video-id="<%= @artist.vimeo %>" data-type="<%= @artist.platform %>"></div>
						</div>
					</div>
				</div>
				<div class="videoMobile mobileME">
					<div class="fitvids responsiveVideo2">
						<% if @artist.platform == 'vimeo' %>
							<div class="plyr js-player">
								<% slide_vimeo_mobile = @artist.vimeo[18..-1] %>
						    	<iframe src="https://player.vimeo.com/video/<%= artist_vimeo_mobile %>" 
								width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen>
								</iframe>
							</div>
						<% else %>
							<div class="plyr js-player">
						    	<div data-video-id="<%= @artist.vimeo %>" data-type="<%= @artist.platform %>"></div>
							</div>
						<% end %>
					</div>
				</div>
				<hr class="projectSeparator" />
				<div class="artist-left">
					<div class="artistSquareImageContainer">
						<div class="artistSquareImage">
							<%= image_tag(@artist.image, :class => "artistSquareImage") %>
						</div>
					</div>
				</div>
				<div class="artist-right">
					<p class="artistDetail"><%= simple_format @artist.description, :class => "artistDetail descriptionSize1" %></p>
				</div>
			</div>
		<% else %>
			<div class="artist-left">
				<div class="artistSquareImageContainer">
					<div class="artistSquareImage">
						<%= image_tag(@artist.image, :class => "artistSquareImage") %>
					</div>
				</div>
			</div>
			<div class="artist-right">
				<p class="artistDetail"><%= simple_format @artist.description, :class => "artistDetail descriptionSize1" %></p>
			</div>
			<div class="artist-bottom">
				<hr class="projectSeparator" />
			</div>
		<% end %>
	</div>
</div>
<script>
	var artistDialog = new FacebookFeedDialog(838327899644745,'<%= request.original_url %>','http://www.splitmusic.co.uk/share_closes');
	artistDialog.addParam('name','<%= @artist.artist_name.split.join(' ') %>');
	artistDialog.addParam('description','<%= @artist.description.split.join(' ') rescue nil %>');
	artistDialog.addParam('picture','<%= @artist.fb_image %>');
</script>