config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'create_new_splitter' }
  
  root 'slides#index'
  
  resources :announcements
  resources :clogos
  resources :announcements do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :artists
  resources :artists do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :admins, :path => "admin"
  resources :works, :path => "placements"
  resources :works do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :releases
  resources :slides, :path => "news"
  resources :releases do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  # resources :customs, :path => "composition"
#   resources :customs do
#     post :update_row_order, on: :collection
#     collection {post :import}
#   end
  resources :researches, :path => "researchlondon"
  resources :researches do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :contacts, :path => "contact"
  resources :share_closes
  resources :newsletters
  resources :showreels
  resources :showreels do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :customvideos
  
  match "admins/artists" => "admins#artists", via: [:get, :post]
  match "admins/customs" => "admins#customs", via: [:get, :post]
  match "admins/placements" => "admins#placements", via: [:get, :post]
  match "admins/releases" => "admins#releases", via: [:get, :post]
  match "admins/customs" => "admins#customs", via: [:get, :post]
  match "admins/researches" => "admins#researches", via: [:get, :post]
  match "admins/slideshow" => "admins#slideshow", via: [:get, :post]
  match "admins/announcements" => "admins#announcements", via: [:get, :post]
  match "admins/newsletter" => "admins#newsletter", via: [:get, :post]
  match "admins/newsletter_blast" => "admins#newsletter_blast", via: [:get, :post]
  match "admins/showreel" => "admins#showreel", via: [:get, :post]
  match "compositions/showreel" => "customs#showreel", via: [:get, :post]
  
end

app/views/admins/_artists.html.erb
<table class="table table-striped" id="sortableArtist">
	<thead>
		<tr>
			<th>Image</th>
			<th>Line1 A</th>
			<th>Line1 B</th>
	 		<th>Line2 A</th>
			<th>Line2 B</th>
	 		<th>Video_URL</th>
			<th>Platform</th>
			<th>Slideshow?</th>
			<th>Newsletter?</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @artists.each do |artist| %>
 			<tr data-item-id=<%= "#{artist.id}" %> class="item">
			<td><%= image_tag(artist.image, class: "thumb2") %></td>
   			<td>
				<span class="rest-in-place" data-url="/artists/<%= artist.slug %>" data-object="artist" 
					data-attribute="slide_title" data-placeholder="empty">
			  		<%= artist.slide_title %>
				</span>
			</td>
   			<td>
				<span class="rest-in-place" data-url="/artists/<%= artist.slug %>" data-object="artist" 
					data-attribute="slide_title2" data-placeholder="empty">
			  		<%= artist.slide_title2 %>
				</span>
			</td>
   			<td>
				<span class="rest-in-place" data-url="/artists/<%= artist.slug %>" data-object="artist" 
					data-attribute="artist_name" data-placeholder="empty">
			  		<%= artist.artist_name %>
				</span>
			</td>
   			<td>
				<span class="rest-in-place" data-url="/artists/<%= artist.slug %>" data-object="artist" 
					data-attribute="track_name" data-placeholder="empty">
			  		<%= artist.track_name %>
				</span>
			</td>
			<td>
				<span class="rest-in-place" data-url="/artists/<%= artist.slug %>" data-object="artist" 
					data-attribute="vimeo" data-placeholder="ADD VIDEO URL">
			  		<%= artist.vimeo %>
				</span>
			</td>
			<td>
				<span class="rest-in-place" data-url="/artists/<%= artist.slug %>" data-object="artist" 
					data-attribute="platform" data-placeholder="ADD VIDEO PLATFORM">
			  		<%= artist.platform %>
				</span>					
			</td>
			<td><%= best_in_place artist, :slideshow, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
			<td><%= best_in_place artist, :newsletter, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
			<td>
				<%= link_to 'Edit', edit_artist_path(artist), class: "btn btn-success" %>
				<%= link_to 'Delete', artist, method: :delete, data: {confirm: "Are you sure you want to delete this record?"}, class: "btn btn-success" %>
			</td>
 			</tr>
		<% end %>
	</tbody>
</table>

app/views/admins/_navigation.html.erb
<div class="col-md-2 border-right">
	<div class="col-md-12"><%= link_to image_tag('logo.png'), root_path, class: "logo2" %></div>
	<div class="col-md-12"><h2 class="titles2" style="margin-top:12px;">Content Management</h2></div>
	<div class="col-md-12">
		<ul id="menu" class="navigation2 clearfix">
			<li class="navButton"><%= link_to 'Slideshow', admins_slideshow_path %></li><br/>
			<li class="navButton"><%= link_to 'Announcements', admins_announcements_path %></li>
			<li class="navButton"><%= link_to 'Artists', admins_artists_path %></li>
			<li class="navButton"><%= link_to 'Releases', admins_releases_path %></li>
			<li class="navButton"><%= link_to 'Placements', admins_placements_path, :class => "navigationButton clearFixer" %></li>
			<!--<li class="navButton"><%#= link_to 'Re-search', admins_researches_path, :class => "navigationButton clearFixer" %></li>-->
			<li class="navButton"><%= link_to 'Blast Newsletter', admins_newsletter_path, :class => "navigationButton clearFixer" %></li>
		</ul>
	</div>
</div>

app/views/admins/announcements.html.erb
<%= render :partial => 'admins/navigation' %>
<div class="col-md-10 cmsTable canScroll">
	<h2 style="color:#5cb85c"><em><%= flash[:notice] %></em></h2>
	<h2 class="titles2 placements">Announcements</h2>
	<div>
		Line 1A & Line 1B are only visible on the slideshow.<br/>
		Line 2A and Line 2B are not displayed for announcements.<br/><br/>
	</div>
	<%= form_tag import_announcements_path, class: "csvInput marginCsv", multipart: true do %>
		<%= file_field_tag :file %><br/>
		<%= submit_tag "Import CSV", class: "btn btn-success marginCsv2" %>
	<% end %>
	 	<%= link_to 'Add New Announcement', new_announcement_path, class: "btn btn-success csvInput"  %>
	<table class="table table-striped" id="sortableAnnouncement">
	 		<thead>
	   		<tr>
				<th>Image</th>
	     		<th>Line1 A</th>
				<th>Line1 B</th>
	     		<th>Line2 A</th>
				<th>Line2 B</th>
				<th>Video URL</th>
				<th>Slideshow?</th>
				<th>Newsletter?</th>
				<th></th>
	   		</tr>
	 		</thead>
	 		<tbody>
	   		<% @announcements.each do |announcement| %>
	     		<tr data-item-id=<%= "#{announcement.id}" %> class="item">
					<td><%= image_tag(announcement.image, class: "thumb2") %></td>
	       			<td>
						<span class="rest-in-place" data-url="/announcements/<%= announcement.slug %>" data-object="announcement" 
							data-attribute="slide_title" data-placeholder="empty">
					  		<%= announcement.slide_title %>
						</span>
					</td>
	       			<td>
						<span class="rest-in-place" data-url="/announcements/<%= announcement.slug %>" data-object="announcement" 
							data-attribute="slide_title2" data-placeholder="empty">
					  		<%= announcement.slide_title2 %>
						</span>
					</td>
	       			<td>
						<span class="rest-in-place" data-url="/announcements/<%= announcement.slug %>" data-object="announcement" 
							data-attribute="artist_name" data-placeholder="empty">
					  		<%= announcement.artist_name %>
						</span>
					</td>
	       			<td>
						<span class="rest-in-place" data-url="/announcements/<%= announcement.slug %>" data-object="announcement" 
							data-attribute="track_name" data-placeholder="empty">
					  		<%= announcement.track_name %>
						</span>
					</td>
					<td>
						<span class="rest-in-place" data-url="/announcements/<%= announcement.slug %>" data-object="announcement" 
							data-attribute="vimeo" data-placeholder="ADD VIDEO URL">
					  		<%= announcement.vimeo %>
						</span>
					</td>
					<td><%= best_in_place announcement, :slideshow, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
					<td><%= best_in_place announcement, :newsletter, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
					<td class="align-right">
						<%= link_to 'Edit', edit_announcement_path(announcement), class: "btn btn-success" %>
						<%= link_to 'Delete', announcement, method: :delete, data: {confirm: "Are you sure you want to delete this record?"}, class: "btn btn-success" %>
					</td>
	     			</tr>
	   		<% end %>
	 		</tbody>
	</table>
</div>

app/views/admins/artists.html.erb
<%= render :partial => 'admins/navigation' %>
<div class="col-md-10 cmsTable canScroll">
	<h2 style="color:#5cb85c"><em><%= flash[:notice] %></em></h2>
	<h2 class="titles2 placements">Artists</h2>
	<div>
		Line 1A & Line 1B are displayed on the slideshow but NOT displayed on the artists index page or artist display page<br/>
		Line 2A and Line 2B are not displayed on the slideshow but ARE displayed on the artists index page & artist display page<br/><br/>
	</div>
	<%= link_to 'Add New Artist', new_artist_path, class: "btn btn-success csvInput3"  %>
	
	<div id="artists"><%= render 'artists' %></div>
</div>

app/views/admins/artists.js.erb
$("#artists").html("<%= escape_javascript(render("artists")) %>");

app/views/admins/customs.html.erb
<%= render :partial => 'admins/navigation' %>
<div class="col-md-10 cmsTable canScroll">
	<h2 style="color:#5cb85c"><em><%= flash[:notice] %></em></h2>
	<h2 class="titles2">Composition management</h2>
	<%= link_to 'Launch Custom Page', customs_path, class: "btn btn-success csvInput3", target: "blank"  %>
	<div id="tabs">
		<ul>
	    	<li><a href="#tabs-1">Grid page management</a></li>
	    	<li><a href="#tabs-2">Artists</a></li>
	    	<li><a href="#tabs-3">Videos</a></li>
	  	</ul>
	  	<div id="tabs-1">
			<h3>Organise how the main composition page looks.<br/><br/>
				You can change the logo here and also decide whether the artists should be displayed <br/>
				randomly (changes each time the page is reloaded) or not.</h3><br/>
			<table class="table table-striped" id="sortableCustom">
			  <thead>
				  <tr>
					  <th>Logo</th>
					  <th>Randomise artist display order?</th>
					  <th></th>
				  </tr>
			  </thead>
			  <tbody>
				  <td><%= image_tag(@clogo.image, class: "thumb2") %></td>
				  <td class="change"><%= best_in_place @clogo, :randombox, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
				  <td class="align-right">
					  <%= link_to 'Edit', edit_clogo_path(@clogo), class: "btn btn-success" %>
				  </td>
			  </tbody>
			</table>
		</div>
		<div id="tabs-2">
			<h3>Add/Edit artists</h3><br/>
			<table class="table table-striped" id="sortableCustom">
				<thead>
			   		<tr>
						<th>Image</th>
			     		<th>Name</th>
						<th>Categories</th>
						<th>Soundcloud</th>
						<th>Wavs? / MP3s?</th>
						<th>Show?</th>
						<th></th>
			   		</tr>
			 	</thead>
			 	<tbody>
		   			<% @customs_d.each do |custom| %>
		     			<tr data-item-id=<%= "#{custom.id}" %> class="item">
							<td><%= image_tag(custom.image, class: "thumb2") %></td>
		       				<td>
								<span class="rest-in-place" data-url="/customs/<%= custom.slug %>" data-object="custom" 
									data-attribute="name" data-placeholder="Name">
						  			<%= custom.name %>
								</span>
							</td>
							<td>
								<span class="rest-in-place" data-url="/customs/<%= custom.slug %>" data-object="custom" 
									data-attribute="genre" data-placeholder="ADD CATEGORIES (Separate with '/')">
									<%= custom.genre %>
								</span>
							</td>
							<td>
								<span class="rest-in-place" data-url="/customs/<%= custom.slug %>" data-object="custom" 
									data-attribute="soundcloud" data-placeholder="ADD SOUNDCLOUD EMBED CODE">
									<%= custom.soundcloud %>
								</span>
							</td>
							<td><% if custom.fullqual? %>Yes<% else %>No<% end %> / <% if custom.lowqual? %>Yes<% else %>No<% end %></td>
							<td class="change"><%= best_in_place custom, :display, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
							<td class="align-right">
								<%= link_to 'Edit', edit_custom_path(custom), class: "btn btn-success" %>
								<%= link_to 'Delete', custom, method: :delete, data: {confirm: "Are you sure you want to delete this record?"}, class: "btn btn-success" %>
							</td>
		     			</tr>
		   			<% end %>
					<% if @customs_nd.count != 0 %>
						<td class="noBackground" colspan="12" style="padding:30px 0px 10px 0px">NOT SORTABLE</td>
						<% @customs_nd.each do |custom| %>
			     			<tr data-item-id=<%= "#{custom.id}" %> class="item">
								<td><%= image_tag(custom.image, class: "thumb2") %></td>
			       				<td>
									<span class="rest-in-place" data-url="/customs/<%= custom.slug %>" data-object="custom" 
										data-attribute="name" data-placeholder="Name">
							  			<%= custom.name %>
									</span>
								</td>
								<td>
									<span class="rest-in-place" data-url="/customs/<%= custom.slug %>" data-object="custom" 
										data-attribute="genre" data-placeholder="ADD CATEGORIES (Separate with '/')">
										<%= custom.genre %>
									</span>
								</td>
								<td>
									<span class="rest-in-place" data-url="/customs/<%= custom.slug %>" data-object="custom" 
										data-attribute="soundcloud" data-placeholder="ADD SOUNDCLOUD EMBED CODE">
										<%= custom.soundcloud %>
									</span>
								</td>
								<td><% if custom.fullqual? %>Yes<% else %>No<% end %> / <% if custom.lowqual? %>Yes<% else %>No<% end %></td>
								<td class="change"><%= best_in_place custom, :display, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
								<td class="align-right">
									<%= link_to 'Edit', edit_custom_path(custom), class: "btn btn-success" %>
									<%= link_to 'Delete', custom, method: :delete, data: {confirm: "Are you sure you want to delete this record?"}, class: "btn btn-success" %>
								</td>
			     			</tr>
			   			<% end %>
					<% end %>
			 	</tbody>
			</table>
			<%= link_to 'Add New Custom Artist', new_custom_path, class: "btn btn-success csvInput2"  %>
	  	</div>
	  	<div id="tabs-3">
			<h3>Add/Edit videos, assign to artists and decide whether or not to add the the showreel page.</h3><br/>
			<table class="table table-striped" id="sortableShowreel">
				<thead>
		   			<tr>
						<th>Video</th>
						<th>Brand Name</th>
		     			<th>Title</th>
						<th>Description?</th>
						<th>Video</th>
						<th>Platform</th>
						<th>Artist</th>
						<th>Showreel?</th>
						<th></th>
		   			</tr>
		 		</thead>
		 		<tbody>
	   				<% @customvideos.each do |cv| %>
	     				<tr data-item-id=<%= "#{cv.id}" %> class="item">
							<td>
								<div class="responsiveVideo frame_container">
									<div class="videoMaster">
										<div class="customVideoDesktop">
											<div class="plyr js-player">
								    			<div data-video-id="<%= cv.vimeo %>" data-type="<%= cv.platform %>"></div>
											</div>
										</div>
									</div>
								</div>
							</td>
	       					<td>
								<span class="rest-in-place" data-url="/customvideos/<%= cv.work_brand_name %>" data-object="customvideo" 
									data-attribute="work_brand_name" data-placeholder="ADD BRAND NAME">
					  				<%= cv.work_brand_name %>
								</span>
							</td>
							<td>
								<span class="rest-in-place" data-url="/customvideos/<%= cv.work_campaign_title %>" data-object="customvideo" 
									data-attribute="work_campaign_title" data-placeholder="ADD CAMPAIGN TITLE">
									<%= cv.work_campaign_title %>
								</span>
							</td>
							<td><% if cv.description? %>Yes<% else %>No<% end %></td>
							<td>
								<span class="rest-in-place" data-url="/customvideos/<%= cv.vimeo %>" data-object="customvideo" 
									data-attribute="vimeo" data-placeholder="VIMEO LINK">
									<%= cv.vimeo %>
								</span>
							</td>
							<td><%= cv.platform %></td>
							<td>
								<%= best_in_place cv, :custom_id, :type => :select, :collection => Custom.all.map { |i| [i.id, i.name] } %>
							</td>
							<td><%= best_in_place cv, :showreel, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>					
							<td class="align-right">
								<%= link_to 'Edit', edit_customvideo_path(cv), class: "btn btn-success" %>
								<%= link_to 'Delete', cv, method: :delete, data: {confirm: "Are you sure you want to delete this record?"}, 
								class: "btn btn-success" %>
							</td>
	     				</tr>
	   				<% end %>
		 		</tbody>
			</table>
			<%= link_to 'Add new video', new_customvideo_path, class: "btn btn-success csvInput2"  %>
	  	</div>
	</div>
</div>

app/views/admins/customvids.html.erb
<%= render :partial => 'admins/navigation' %>
<div class="col-md-10 cmsTable canScroll">
	<h2 style="color:#5cb85c"><em><%= flash[:notice] %></em></h2>
	<h2 class="titles2 placements">Bespoke Videos</h2>
	<%= link_to 'Add New Custom Video', new_customvid_path, class: "btn btn-success csvInput2"  %>
	<%= link_to 'Launch Custom Page', customs_path, class: "btn btn-success csvInput3", target: "blank"  %>
	<table class="table table-striped" id="sortableCustomvid">
	 		<thead>
	   		<tr>
	     		<th>Vimeo ID</th>
	     		<th>Brand Name</th>
				<th>Campaign Title</th>
				<th>Artist</th>
				<th></th>
	   		</tr>
	 		</thead>
	 		<tbody>
	   		<% @customvids.each do |customvid| %>
	     			<tr data-item-id=<%= "#{customvid.id}" %> class="item">
	       			<td>
						<span class="rest-in-place" data-url="/customvids/<%= customvid.id %>" data-object="customvid" data-attribute="vimeo_id" data-placeholder="Vimeo ID">
					  		<%= customvid.vimeo_id %>
						</span>
					</td>
					<td>
						<span class="rest-in-place" data-url="/customvids/<%= customvid.id %>" data-object="customvid" data-attribute="brand_name" data-placeholder="Brand Name">
					  		<%= customvid.brand_name %>
						</span>
					</td>
					<td>
						<span class="rest-in-place" data-url="/customvids/<%= customvid.id %>" data-object="customvid" data-attribute="campaign_title" data-placeholder="Campaign Title">
					  		<%= customvid.campaign_title %>
						</span>
					</td>
					<td><%= customvid.custom.name %></td>
					<td>
						<%= link_to 'Edit', edit_customvid_path(customvid), class: "btn btn-success" %>
						<%= link_to 'Delete', customvid, method: :delete, data: {confirm: "Are you sure you want to delete this record?"}, class: "btn btn-success" %>
					</td>
	     			</tr>
	   		<% end %>
	 		</tbody>
	</table>
</div>

app/views/admins/newsletter.html.erb
<%= render :partial => 'admins/navigation' %>
<div class="col-md-10 cmsTable canScroll">
	<h2 style="color:#5cb85c"><em><%= flash[:notice] %></em></h2>
	<%= link_to 'Launch Blast Newsletter', newsletters_path, class: "btn btn-success", target: "blank", style: "float:left;clear:both;"  %>
	<table class="table table-striped" id="">
	 		<thead>
	   		<tr>
				<th>Rectangular image</th>
	     		<th>Title</th>
				<th>Subtitle</th>
				<th>Type of record</th>
				<th>Newsletter description</th>
				<th>Newsletter?</th>
				<th>Newsletter grid Position</th>
	   		</tr>
	 		</thead>
	 		<tbody>
	   		<% @sorted_newsletters.each do |nl| %>
     			<tr data-item-id=<%= "" %> class="item">
					<td><%= image_tag(nl.hero, class: "thumb3") %></td>
       				<td><%= best_in_place nl, :nltitle %></td>
					<td><%= best_in_place nl, :nlsubtitle %></td>
					<td><%= nl.class.to_s.upcase  %></td>
					<td width="700px"><%= best_in_place nl, :nldescription %></td>
					<td><%= best_in_place nl, :newsletter, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
					<td><%= best_in_place nl, :newsletterposition %></td>
     			</tr>
	   		<% end %>
	 		</tbody>
	</table>
</div>

app/views/admins/newsletter_old.html.erb
<%= render :partial => 'admins/navigation' %>
<div class="col-md-10 cmsTable canScroll">
	<h2 style="color:#5cb85c"><em><%= flash[:notice] %></em></h2>
	<%= link_to 'Launch Newsletter', newsletters_path, class: "btn btn-success", target: "blank", style: "float:left;clear:both;"  %>
	<%= link_to 'Edit Newsletter images and links', edit_newsletter_path(@first_newsletter), class: "btn btn-success", 
	target: "blank", style: "margin-left:5px;"  %><br/>
	<h2 class="titles2 placements" style="float:left;clear:both!important;margin-top:40px;"><%= best_in_place @first_newsletter, :title1 %></h2>
	<table class="table table-striped" id="">
	 		<thead>
	   		<tr>
				<th>Square image</th>
				<th>Rectangular image</th>
	     		<th>Title</th>
				<th>Subtitle</th>
				<th>Newsletter?</th>
				<th>Newsletter description</th>
				<th>Newsletter grid Position</th>
	   		</tr>
	 		</thead>
	 		<tbody>
	   		<% @sorted_newsletters.each do |nl| %>
     			<tr data-item-id=<%= "" %> class="item">
					<td>
						<% if nl.slide_image? %>
							<%= image_tag(nl.slide_image, class: "thumb3") %>
						<% else %>
							<%= image_tag(nl.image, class: "thumb3") %>
						<% end %>
					</td>
					<td><%= image_tag(nl.hero, class: "thumb3") %></td>
       				<td><%= best_in_place nl, :nltitle %></td>
					<td><%= best_in_place nl, :nlsubtitle %></td>
					<td><%= best_in_place nl, :newsletter, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
					<td width="700px"><%= best_in_place nl, :nldescription %></td>
					<td><%= best_in_place nl, :newsletterposition %></td>
     			</tr>
	   		<% end %>
	 		</tbody>
	</table><br/><hr/><br/>
	<h2 class="titles2 placements"><%= best_in_place @first_newsletter, :title2 %></h2>
	<table class="table table-striped" id="">
	 		<thead>
	   		<tr>
				<th>Image</th>
	     		<th>Title</th>
				<th>Download link?</th>
				<th>Newsletter?</th>
				<th>Newsletter list Position</th>
	   		</tr>
	 		</thead>
	 		<tbody>
	   		<% @newsletters_releases.each do |nl| %>
     			<tr data-item-id=<%= "" %> class="item">
					<td><%= image_tag(nl.image, class: "thumb3") %></td>
       				<td><%= best_in_place nl, :title %></td>
					<td><% if nl.downloadlink? %>Yes<% else %>No<% end %></td>
					<td><%= best_in_place nl, :newsletter, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
					<td><%= best_in_place nl, :newsletterposition %></td>
     			</tr>
	   		<% end %>
	 		</tbody>
	</table>
</div>

app/views/admins/placements.js.erb
$("#works").html("<%= escape_javascript(render("works")) %>");

app/views/admins/releases.html.erb
<%= render :partial => 'admins/navigation' %>
<div class="col-md-10 cmsTable canScroll">
	<h2 style="color:#5cb85c"><em><%= flash[:notice] %></em></h2>
	<h2 class="titles2 placements">Releases</h2>
	<div>
		Line 1A & Line 1B are displayed on the slideshow but NOT displayed on the releases index page or release display page<br/>
		Line 2A and Line 2B are not displayed on the slideshow but ARE displayed on the releases index page & release display page<br/><br/>
	</div>
	<%= form_tag import_releases_path, class: "csvInput marginCsv", multipart: true do %>
		<%= file_field_tag :file %><br/>
		<%= submit_tag "Import CSV", class: "btn btn-success marginCsv2" %>
	<% end %>
	<%= link_to 'Add New Release', new_release_path, class: "btn btn-success csvInput"  %>
	<div style="float:right;">
		<%= form_tag admins_releases_path, :method => 'get', :id => "releases_search" do %>
			<p class="csvInput4" style="padding-left:10px;padding-top:0px;">
				<%= text_field_tag :search, params[:search], :style => "margin-left:10px;" %>
				<%= submit_tag "Search", :title => nil, :class => "btn btn-success", :style => "margin-left:6px;" %>
			</p>
		<% end %>
	</div>
	<div id="releases"><%= render 'releases' %></div>
</div>

app/views/admins/showreel.html.erb
<%= render :partial => 'admins/navigation' %>
<div class="col-md-10 cmsTable canScroll">
	<h2 style="color:#5cb85c"><em><%= flash[:notice] %></em></h2>
	<h2 class="titles2">Showreel pieces</h2>
	<%= link_to 'Add New Showreel video', new_showreel_path, class: "btn btn-success csvInput2"  %>
	<%= link_to 'Launch Showreel Page', compositions_showreel_path, class: "btn btn-success csvInput3", target: "blank"  %>
	<table class="table table-striped" id="sortableShowreel">
		<thead>
	   		<tr>
				<th>Brand Name</th>
	     		<th>Campaign Title</th>
				<th>Description?</th>
				<th>Video</th>
				<th>Platform</th>
				<th>Slideshow Position</th>
				<th>Showreel Page?</th>
	   		</tr>
	 	</thead>
	 	<tbody>
   			<% @sorted_showreelvideos.each do |showreel| %>
     			<tr data-item-id=<%= "#{showreel.id}" %> class="item">
       				<td>
						<span class="rest-in-place" data-url="/showreels/<%= showreel.work_brand_name %>" data-object="showreel" 
							data-attribute="work_brand_name" data-placeholder="ADD BRAND NAME">
				  			<%= showreel.work_brand_name %>
						</span>
					</td>
					<td>
						<span class="rest-in-place" data-url="/showreels/<%= showreel.work_campaign_title %>" data-object="showreel" 
							data-attribute="work_campaign_title" data-placeholder="ADD CAMPAIGN TITLE">
							<%= showreel.work_campaign_title %>
						</span>
					</td>
					<td><% if showreel.description? %>Yes<% else %>No<% end %></td>
					<td>
						<span class="rest-in-place" data-url="/showreels/<%= showreel.vimeo %>" data-object="showreel" 
							data-attribute="vimeo" data-placeholder="VIMEO LINK">
							<%= showreel.vimeo %>
						</span>
					</td>
					<td><%= showreel.platform %></td>
					<td><%= best_in_place showreel, :showreelposition %></td>
					<td><%= best_in_place showreel, :showreel, as: :checkbox, collection: {false: "No", true: "Yes"} %></td>
     			</tr>
   			<% end %>
	 	</tbody>
	</table>
</div>