config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'create_new_splitter' }
  
  root 'slides#index'
  
  resources :announcements
  resources :clogos
  resources :announcements do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :artists
  resources :artists do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :admins, :path => "admin"
  resources :works, :path => "placements"
  resources :works do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :releases
  resources :slides, :path => "news"
  resources :releases do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  # resources :customs, :path => "composition"
#   resources :customs do
#     post :update_row_order, on: :collection
#     collection {post :import}
#   end
  resources :researches, :path => "researchlondon"
  resources :researches do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :contacts, :path => "contact"
  resources :share_closes
  resources :newsletters
  resources :showreels
  resources :showreels do
    post :update_row_order, on: :collection
    collection {post :import}
  end
  resources :customvideos
  
  match "admins/artists" => "admins#artists", via: [:get, :post]
  match "admins/customs" => "admins#customs", via: [:get, :post]
  match "admins/placements" => "admins#placements", via: [:get, :post]
  match "admins/releases" => "admins#releases", via: [:get, :post]
  match "admins/customs" => "admins#customs", via: [:get, :post]
  match "admins/researches" => "admins#researches", via: [:get, :post]
  match "admins/slideshow" => "admins#slideshow", via: [:get, :post]
  match "admins/announcements" => "admins#announcements", via: [:get, :post]
  match "admins/newsletter" => "admins#newsletter", via: [:get, :post]
  match "admins/newsletter_blast" => "admins#newsletter_blast", via: [:get, :post]
  match "admins/showreel" => "admins#showreel", via: [:get, :post]
  match "compositions/showreel" => "customs#showreel", via: [:get, :post]
  
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_action :authenticate_user!, :except => ["index", "show"]
  
    def new
      @release = Release.new
    end

    def create
      @release = Release.create(release_params)
      respond_to do |format|
        format.html { redirect_to admins_releases_path }
      end
    end

    def edit
      @release = Release.find_by_slug(params[:id])
    end

    def update   
      @release = Release.find_by_slug(params[:id])
      if @release.update_attributes(release_params)
        respond_to do |format|
         format.html { redirect_to admins_releases_path }
         format.json { render :json => @release }
        end
      else
        respond_to do |format|
          format.html { render :action  => :edit } # edit.html.erb
          format.json { render :nothing =>  true }
        end
      end
    end

    def destroy
      @release = Release.find_by_slug(params[:id])
      @release.destroy
      respond_to do |format|
        format.html { redirect_to admins_releases_path }
      end
    end
    
    def import
      Release.import(params[:file])
      redirect_to admins_releases_path, notice: "Releases imported!" 
    end
    
    def index
      @releases = Release.rank(:row_order).all
      set_meta_tags :og => {
        :url => "#{@currentUrl}",
        :title    => 'Split Music | Releases',
        :description => '21st Century Music Publishing | Unique Music to Picture'
      }
      set_meta_tags twitter: {
        card: "summary_large_image",
        site: "@fairsplitmusic",
        title: "Split Music | Releases",
        description: "21st Century Music Publishing | Unique Music to Picture"
      }
    end
    
    def show
      @release = Release.find_by_slug(params[:id])
      set_meta_tags og: {
        url: "#{@currentUrl}",
        image: "#{@release.fb_image}",
        title: "#{@release.title}",
        description: "#{@release.description}",
        type: "musician"
      }
      set_meta_tags twitter: {
        card: "summary_large_image",
        site: "@fairsplitmusic",
        title: "#{@release.title}",
        description: "#{@release.description}",
        image: "#{@release.fb_image}"
      }
      render :show, flush: true
    end

    def update_row_order
      @release = Release.find(release_params[:release_id])
      @release.row_order_position = release_params[:row_order_position]
      @release.save
      render nothing: true # this is a POST action, updates sent via AJAX, no view rendered
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_release
      @release = Release.find(params[:id])
    end
    
    def release_params
      params.require(:release).permit(:release_id, :title, :soundcloud, :description, :image, :fb_image, :hero, :row_order_position, :nltitle, 
      :nlsubtitle, :nldescription, :slideshow, :slide_image, :slide_title ,:slide_title2, :slide_title3, :Slideshowposition, :newsletter, 
      :newsletterposition, :downloadlink, :platform, :vimeo, :artist_name, :track_name, :artist_id)
    end
  
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/releases/_form.html.erb
<div class="deviseStyling abouts marginTopOverride canScroll">
	<h2 class="titles">Add your release here!</h2>
	<%= bootstrap_form_for(@release) do |f| %>
		<div class="col-md-12" style="background-color: rgba(113, 113, 113, 0.5);padding:10px;border-radius:6px;margin:0px 0px 10px 0px">
			<h2 style="margin:10px;">IMAGES</h2>
			<div class="vimeoSectionInForm">
				<div class="textField"><%= f.file_field :image, label: "Square image (crop to 400px X 400px)" %>
					<% if @release.image.exists? %>
						<p class="existingImageName">{ Current Image: "<%= @release.image_file_name %>" }</p>
					<% end %>
				</div>
				<div class="textField"><%= f.file_field :slide_image, label: "Slideshow image (crop to 1115px X 952px)" %>
					<% if @release.slide_image.exists? %>
						<p class="existingImageName">{ Current Image: "<%= @release.slide_image_file_name %>" }</p>
					<% end %>
				</div>
				<div class="textField"><%= f.file_field :fb_image, label: "Facebook image (crop to 1200px X 630px)" %>
					<% if @release.fb_image.exists? %>
						<p class="existingImageName">{ Current Image: "<%= @release.fb_image_file_name %>" }</p>
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-6" style="background-color: rgba(113, 113, 113, 0.5);padding:10px;border-radius:6px;margin:0px 0px 0px 0px">
			<h2 style="margin:10px;">MAIN RELEASE CONTENT</h2>
			<div class="vimeoSectionInForm">
				<div class="textField2"><%= f.text_field :slide_title, label: "Line1 A" %></div>
				<div class="textField2"><%= f.text_field :slide_title2, label: "Line1 B" %></div>
				<div class="textField2"><%= f.text_field :artist_name, label: "Line2 A (Artist Name)" %></div>
				<div class="textField2"><%= f.text_field :track_name, label: "Line2 B (Release Title)" %></div>
				<div class="textField2"><%= f.text_field :vimeo, label: "Video URL" %></div>
				<div class="textField2">
					<%= f.select :platform, options_for_select(["vimeo", "youtube"], @release.platform) %>
				</div>
				<div class="textField smallText"><%= f.check_box :slideshow, label: "Add to slideshow?" %></div>
			</div>
			<div class="vimeoSectionInForm"><%= f.text_area :description, label: "Description" %></div>
		</div>
		<div class="col-md-6" style="background-color: rgba(113, 113, 113, 0.5);padding:10px;border-radius:6px;width:48%; margin:0px 1%;">
			<h2 style="margin:10px;">NEWSLETTER CONTENT</h2>
			<div class="vimeoSectionInForm">
				<div class="textField smallText"><%= f.check_box :newsletter, label: "Add to newsletter?" %></div>
				<div class="textField"><%= f.text_field :downloadlink, label: "MP3 Download link" %></div>
				<div class="textField"><%= f.file_field :hero, label: "Newsletter hero image (crop to 564px X 235px before upload)" %>
					<% if @release.hero.exists? %>
						<p class="existingImageName">{ Current Image: "<%= @release.hero_file_name %>" }</p>
					<% end %>
				</div>
			</div>
			<div class="vimeoSectionInForm">
				<div class="textField2"><%= f.text_field :nltitle, label: "Newsletter title" %></div>
				<div class="textField2"><%= f.text_field :nlsubtitle, label: "Newsletter title 2" %></div>
			</div>
			<div class="vimeoSectionInForm"><%= f.text_area :nldescription, label: "Newsletter description" %></div>
		</div>
	  	<div class="buttons" style="float:left;clear:both;margin:25px -6px;">
			<div class="submitLarge"><%= f.submit 'Submit', class: "btn btn-success"  %></div>
			<div class="cancelButton"><%= link_to('Cancel', :back ,class: "btn btn-success")  %></div>
		</div>
	<% end %>
</div>

app/views/releases/edit.html.erb
<%= render 'form' %>

app/views/releases/index.html.erb
<div class="canScroll" id="releaseScrollPosition">
	<div class="col-md-12">
		<% @releases.each do |release| %>
		<input type="hidden" value=<%= release.id %> class="modal-object-id">
		<a href="<%= release_path(release) %>" class="positionButtonRelease">
			<div class="col-md-4b artistContainer">
				<div class="artist">
					<div class="info-wrapper">
						<h5 class="colour notBold"><%= release.artist_name %><br/><%= release.track_name %></h5>
					</div>
					<%= image_tag "https://d9gj9tfjl21as.cloudfront.net/ajaxBig2.gif", data:{ src: image_path(release.image) }, class: 'lazy lazyload' %>
				</div>
			</div>
		</a>
		<% end %>
	</div>
</div>

app/views/releases/new.html.erb
<%= render 'form' %>

app/views/releases/show.html.erb
<div class="canScroll">	
	<div class="artistInfo">
		<%= link_to '', releases_path, :class => "closeIcon" %>
		<h1 class="artistName titleSize1"><%= @release.artist_name %> / <%= @release.track_name %></h1>
		<hr class="artistSeparator" />
		<% if @release.vimeo? %>
			<div class="videoMaster">
				<div class="videoDesktop desktopME">
					<div class="fitvids responsiveVideo2">
						<div class="plyr js-player">
						    <div data-video-id="<%= @release.vimeo %>" data-type="<%= @release.platform %>"></div>
						</div>
					</div>
				</div>
				<div class="videoMobile mobileME">
					<div class="fitvids responsiveVideo2">
						<% if @release.platform == 'vimeo' %>
							<div class="plyr js-player">
								<% release_vimeo_mobile = @release.vimeo[18..-1] %>
						    	<iframe src="https://player.vimeo.com/video/<%= release_vimeo_mobile %>" 
								width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen>
								</iframe>
							</div>
						<% else %>
							<div class="plyr js-player">
						    	<div data-video-id="<%= @release.vimeo %>" data-type="<%= @release.platform %>"></div>
							</div>
						<% end %>
					</div>
				</div>
				<hr class="projectSeparator" />
				<div class="artist-left">
					<div class="artistSquareImageContainer">
						<div class="artistSquareImage">
							<%= image_tag(@release.image, :class => "artistSquareImage") %>
						</div>
					</div>
				</div>
				<div class="artist-right">
					<p class="artistDetail"><%= simple_format @release.description, :class => "artistDetail descriptionSize1" %></p>
				</div>
			</div>
		<% else %>
			<div class="artist-left">
				<div class="artistSquareImageContainer">
					<div class="artistSquareImage">
						<%= image_tag(@release.image, :class => "artistSquareImage") %>
					</div>
				</div>
			</div>
			<div class="artist-right">
				<p class="artistDetail"><%= simple_format @release.description, :class => "artistDetail descriptionSize1" %></p>
			</div>
			<div class="artist-bottom">
				<hr class="projectSeparator" />
			</div>
		<% end %>
	</div>
</div>
<script>
	var artistDialog = new FacebookFeedDialog(838327899644745,'<%= request.original_url %>','http://www.splitmusic.co.uk/share_closes');
	releaseDialog.addParam('name','<%= @release.track_name.split.join(' ') %>');
	releaseDialog.addParam('description','<%= @release.description.split.join(' ') rescue nil %>');
	releaseDialog.addParam('picture','<%= @release.fb_image %>');
</script>
	
	